name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject Version into module.json
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          sed -i 's/"version": ".*"/"version": "'$VERSION'"/' module.json

      - name: Commit version bump to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add module.json
          git commit -m "Auto-update version to ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          # fetch et rebase pour éviter les conflits si des commits ont été poussés entre temps
          git fetch origin main
          git rebase origin/main
          git push origin HEAD:main

      - name: Update Download URL for Release Asset
        run: |
          # The release asset module.json gets a specific download URL so historical versions can be installed
          sed -i 's|"download": ".*"|"download": "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip"|' module.json

      - name: Create Module Zip
        run: |
          mkdir /tmp/sra2-xp-cash
          rsync -a . /tmp/sra2-xp-cash/ --exclude .git --exclude .github --exclude .gitignore
          cd /tmp
          zip -r $GITHUB_WORKSPACE/module.zip sra2-xp-cash/
          cd $GITHUB_WORKSPACE

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} module.zip module.json --clobber
